# evtx-analyzer/docker-compose.yaml
version: '3.8'

services:
  chayabusaw:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chayabusaw-app
    ports:
      - "8000:8000"
    volumes:
      # Persistently store the analysis reports on the host
      - ./analysis_results:/app/results
      # Persistently store the parsed JSONL files on the host
      - ./evtx_jsonl_output:/app/jsonl_output
      # Load in custom Sigma rules
      - ./custom-sigma-rules:/opt/sigma/custom/rules
      # Load in custom chainsaw rules
      - ./custom-chainsaw-rules:/chainsaw-rules
      # Persistently store application logs on the host
      - ./logs:/logs
    restart: unless-stopped